# ==============================================================================
# Mini Active Directory (mini-ad) Module Invocation
# ------------------------------------------------------------------------------
# Purpose:
#   - Invoke the reusable "mini-ad" module to provision an Ubuntu AD DC.
#   - Provide networking, DNS, and authentication inputs.
#   - Pass a rendered users JSON blob used during VM bootstrap.
# ==============================================================================

module "mini_ad" {
  # ----------------------------------------------------------------------------
  # Module source
  # ----------------------------------------------------------------------------
  source = "github.com/mamonaco1973/module-azure-mini-ad"

  # ----------------------------------------------------------------------------
  # Core deployment settings
  # ----------------------------------------------------------------------------
  location = var.resource_group_location # Azure region
  netbios  = var.netbios                 # NetBIOS domain name (e.g., MCLOUD)
  realm    = var.realm                   # Kerberos realm (DNS domain in uppercase)
  dns_zone = var.dns_zone                # DNS zone (e.g., mcloud.mikecloud.com)

  # ----------------------------------------------------------------------------
  # Networking
  # ----------------------------------------------------------------------------
  vnet_id    = azurerm_virtual_network.ad_vnet.id # VNet for the AD deployment
  subnet_id  = azurerm_subnet.mini_ad_subnet.id   # Subnet for the AD VM
  depends_on = [
    azurerm_nat_gateway.vm_nat_gateway,
    azurerm_subnet_nat_gateway_association.mini_ad_nat_assoc,
  ]

  # ----------------------------------------------------------------------------
  # Identity and bootstrap inputs
  # ----------------------------------------------------------------------------
  user_base_dn      = var.user_base_dn                      # LDAP base DN for users
  users_json        = local.users_json                      # Rendered JSON for user create
  ad_admin_password = random_password.admin_password.result # AD domain Admin password
  admin_password    = random_password.sysadmin_password.result
}

# ==============================================================================
# Local: users_json
# ------------------------------------------------------------------------------
# Purpose:
#   - Render scripts/users.json.template into a single JSON blob.
#   - Inject generated passwords for demo users at apply time.
#   - Provide the JSON to the mini-ad module for automated user creation.
# ==============================================================================

locals {
  users_json = templatefile("./scripts/users.json.template", {
    # --------------------------------------------------------------------------
    # Directory naming inputs
    # --------------------------------------------------------------------------
    USER_BASE_DN = var.user_base_dn # Base DN for placing users in LDAP
    DNS_ZONE     = var.dns_zone     # AD-integrated DNS zone
    REALM        = var.realm        # Kerberos realm (uppercase FQDN)
    NETBIOS      = var.netbios      # NetBIOS domain name

    # --------------------------------------------------------------------------
    # Demo user passwords (generated by random_password resources)
    # --------------------------------------------------------------------------
    jsmith_password = random_password.jsmith_password.result
    edavis_password = random_password.edavis_password.result
    rpatel_password = random_password.rpatel_password.result
    akumar_password = random_password.akumar_password.result
  })
}
